version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SomeSuperStrongPW
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 80:80
      - 443:443
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: SomeSuperStrongPW
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: lonavlabazaar.app
      PS_ENABLE_SSL: 1
    networks:
      - prestashop_network
networks:
    prestashop_network: